// <auto-generated />
using System;
using EarlyLearner.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EarlyLearner.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260622091950_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EarlyLearner.Domain.CoreContext.Entities.StoredFile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("file_name");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("media_type");

                    b.Property<long>("SizeInBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_in_bytes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_key");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id")
                        .HasName("pk_stored_files");

                    b.HasIndex("HouseholdId", "StorageKey")
                        .IsUnique()
                        .HasDatabaseName("ix_stored_files_household_id_storage_key");

                    b.ToTable("stored_files", (string)null);
                });

            modelBuilder.Entity("EarlyLearner.Domain.IdentityContext.Entities.Carer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_carers");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_carers_user_id");

                    b.HasIndex("HouseholdId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_carers_household_id_user_id");

                    b.ToTable("carers", (string)null);
                });

            modelBuilder.Entity("EarlyLearner.Domain.IdentityContext.Entities.Child", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("given_name");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id")
                        .HasName("pk_children");

                    b.HasIndex("HouseholdId", "FirstName")
                        .HasDatabaseName("ix_children_household_id_given_name");

                    b.ToTable("children", (string)null);
                });

            modelBuilder.Entity("EarlyLearner.Domain.IdentityContext.Entities.Household", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id")
                        .HasName("pk_households");

                    b.ToTable("households", (string)null);
                });

            modelBuilder.Entity("EarlyLearner.Domain.IdentityContext.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("ExternalObjectId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_object_id");

                    b.Property<string>("ExternalTenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_tenant_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("EarlyLearner.Domain.LearningContext.Entities.CompletedActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<Guid>("DailyLogId")
                        .HasColumnType("uuid")
                        .HasColumnName("daily_log_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id")
                        .HasName("pk_completed_activities");

                    b.HasIndex("DailyLogId")
                        .HasDatabaseName("ix_completed_activities_daily_log_id");

                    b.ToTable("completed_activities", (string)null);
                });

            modelBuilder.Entity("EarlyLearner.Domain.LearningContext.Entities.DailyLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<DateOnly>("LogDate")
                        .HasColumnType("date")
                        .HasColumnName("log_date");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id")
                        .HasName("pk_daily_logs");

                    b.HasIndex("ChildId")
                        .HasDatabaseName("ix_daily_logs_child_id");

                    b.HasIndex("HouseholdId", "ChildId", "LogDate")
                        .IsUnique()
                        .HasDatabaseName("ix_daily_logs_household_id_child_id_log_date");

                    b.ToTable("daily_logs", (string)null);
                });

            modelBuilder.Entity("EarlyLearner.Domain.LearningContext.Entities.Observation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(2400)
                        .HasColumnType("character varying(2400)")
                        .HasColumnName("note");

                    b.Property<DateOnly>("ObservedOn")
                        .HasColumnType("date")
                        .HasColumnName("observed_on");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id")
                        .HasName("pk_observations");

                    b.HasIndex("ChildId")
                        .HasDatabaseName("ix_observations_child_id");

                    b.HasIndex("HouseholdId", "ChildId", "ObservedOn")
                        .HasDatabaseName("ix_observations_household_id_child_id_observed_on");

                    b.ToTable("observations", (string)null);
                });

            modelBuilder.Entity("EarlyLearner.Domain.LearningContext.Entities.ReadingEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("author");

                    b.Property<string>("ChildResponse")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("character varying(1200)")
                        .HasColumnName("child_response");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<Guid>("DailyLogId")
                        .HasColumnType("uuid")
                        .HasColumnName("daily_log_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id")
                        .HasName("pk_reading_entries");

                    b.HasIndex("DailyLogId")
                        .HasDatabaseName("ix_reading_entries_daily_log_id");

                    b.ToTable("reading_entries", (string)null);
                });

            modelBuilder.Entity("EarlyLearner.Domain.LearningContext.Entities.RoutineEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<Guid>("DailyLogId")
                        .HasColumnType("uuid")
                        .HasColumnName("daily_log_id");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("character varying(1200)")
                        .HasColumnName("notes");

                    b.Property<string>("RoutineName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("routine_name");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id")
                        .HasName("pk_routine_entries");

                    b.HasIndex("DailyLogId")
                        .HasDatabaseName("ix_routine_entries_daily_log_id");

                    b.ToTable("routine_entries", (string)null);
                });

            modelBuilder.Entity("EarlyLearner.Domain.PlanningContext.Entities.Goal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id")
                        .HasName("pk_goals");

                    b.HasIndex("ChildId")
                        .HasDatabaseName("ix_goals_child_id");

                    b.HasIndex("HouseholdId", "ChildId", "Status")
                        .HasDatabaseName("ix_goals_household_id_child_id_status");

                    b.ToTable("goals", (string)null);
                });

            modelBuilder.Entity("EarlyLearner.Domain.PlanningContext.Entities.LearningPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<string>("Focus")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("focus");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id")
                        .HasName("pk_learning_plans");

                    b.HasIndex("ChildId")
                        .HasDatabaseName("ix_learning_plans_child_id");

                    b.HasIndex("HouseholdId", "ChildId")
                        .HasDatabaseName("ix_learning_plans_household_id_child_id");

                    b.ToTable("learning_plans", (string)null);
                });

            modelBuilder.Entity("EarlyLearner.Domain.PlanningContext.Entities.PlannedLearningSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<Guid>("LearningPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("learning_plan_id");

                    b.Property<DateOnly>("PlannedDate")
                        .HasColumnType("date")
                        .HasColumnName("planned_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id")
                        .HasName("pk_planned_learning_sessions");

                    b.HasIndex("LearningPlanId", "PlannedDate")
                        .HasDatabaseName("ix_planned_learning_sessions_learning_plan_id_planned_date");

                    b.ToTable("planned_learning_sessions", (string)null);
                });

            modelBuilder.Entity("EarlyLearner.Domain.ReadinessContext.Entities.EvidenceReference", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<Guid>("EvidenceRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("evidence_record_id");

                    b.Property<DateOnly>("ObservedOn")
                        .HasColumnType("date")
                        .HasColumnName("observed_on");

                    b.Property<Guid>("ReadinessOutcomeId")
                        .HasColumnType("uuid")
                        .HasColumnName("readiness_outcome_id");

                    b.Property<int>("ReadinessOutcomeProgressId")
                        .HasColumnType("integer")
                        .HasColumnName("readiness_outcome_progress_id");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("source_type");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)")
                        .HasColumnName("summary");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id")
                        .HasName("pk_evidence_references");

                    b.HasIndex("ReadinessOutcomeId")
                        .HasDatabaseName("ix_evidence_references_readiness_outcome_id");

                    b.HasIndex("ReadinessOutcomeProgressId")
                        .HasDatabaseName("ix_evidence_references_readiness_outcome_progress_id");

                    b.ToTable("evidence_references", (string)null);
                });

            modelBuilder.Entity("EarlyLearner.Domain.ReadinessContext.Entities.PortfolioItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("character varying(1200)")
                        .HasColumnName("caption");

                    b.Property<DateOnly>("CapturedOn")
                        .HasColumnType("date")
                        .HasColumnName("captured_on");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id")
                        .HasName("pk_portfolio_items");

                    b.HasIndex("ChildId")
                        .HasDatabaseName("ix_portfolio_items_child_id");

                    b.HasIndex("HouseholdId", "ChildId", "CapturedOn")
                        .HasDatabaseName("ix_portfolio_items_household_id_child_id_captured_on");

                    b.ToTable("portfolio_items", (string)null);
                });

            modelBuilder.Entity("EarlyLearner.Domain.ReadinessContext.Entities.ReadinessOutcome", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("character varying(1200)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id")
                        .HasName("pk_readiness_outcomes");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_readiness_outcomes_code");

                    b.HasIndex("Category", "SortOrder")
                        .HasDatabaseName("ix_readiness_outcomes_category_sort_order");

                    b.ToTable("readiness_outcomes", (string)null);
                });

            modelBuilder.Entity("EarlyLearner.Domain.ReadinessContext.Entities.ReadinessOutcomeProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ReadinessOutcomeId")
                        .HasColumnType("uuid")
                        .HasColumnName("readiness_outcome_id");

                    b.Property<Guid>("ReadinessProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("readiness_profile_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_readiness_outcome_progresses");

                    b.HasIndex("ReadinessOutcomeId")
                        .HasDatabaseName("ix_readiness_outcome_progresses_readiness_outcome_id");

                    b.HasIndex("ReadinessProfileId", "ReadinessOutcomeId")
                        .IsUnique()
                        .HasDatabaseName("ix_readiness_outcome_progresses_readiness_profile_id_readiness");

                    b.ToTable("readiness_outcome_progresses", (string)null);
                });

            modelBuilder.Entity("EarlyLearner.Domain.ReadinessContext.Entities.ReadinessProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id")
                        .HasName("pk_readiness_profiles");

                    b.HasIndex("ChildId")
                        .HasDatabaseName("ix_readiness_profiles_child_id");

                    b.HasIndex("HouseholdId", "ChildId")
                        .IsUnique()
                        .HasDatabaseName("ix_readiness_profiles_household_id_child_id");

                    b.ToTable("readiness_profiles", (string)null);
                });

            modelBuilder.Entity("EarlyLearner.Domain.ReadinessContext.Entities.SuggestedNextStep", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<Guid>("ReadinessOutcomeId")
                        .HasColumnType("uuid")
                        .HasColumnName("readiness_outcome_id");

                    b.Property<Guid>("ReadinessProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("readiness_profile_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)")
                        .HasColumnName("text");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id")
                        .HasName("pk_suggested_next_steps");

                    b.HasIndex("ReadinessOutcomeId")
                        .HasDatabaseName("ix_suggested_next_steps_readiness_outcome_id");

                    b.HasIndex("ReadinessProfileId")
                        .HasDatabaseName("ix_suggested_next_steps_readiness_profile_id");

                    b.ToTable("suggested_next_steps", (string)null);
                });

            modelBuilder.Entity("EarlyLearner.Infrastructure.Persistence.Configurations.LearningContext.CompletedActivityConfig+CompletedActivityReadinessOutcome", b =>
                {
                    b.Property<Guid>("CompletedActivityId")
                        .HasColumnType("uuid")
                        .HasColumnName("completed_activity_id");

                    b.Property<Guid>("ReadinessOutcomeId")
                        .HasColumnType("uuid")
                        .HasColumnName("readiness_outcome_id");

                    b.HasKey("CompletedActivityId", "ReadinessOutcomeId")
                        .HasName("pk_completed_activity_readiness_outcomes");

                    b.HasIndex("ReadinessOutcomeId")
                        .HasDatabaseName("ix_completed_activity_readiness_outcomes_readiness_outcome_id");

                    b.ToTable("completed_activity_readiness_outcomes", (string)null);
                });

            modelBuilder.Entity("EarlyLearner.Infrastructure.Persistence.Configurations.LearningContext.CompletedActivityConfig+CompletedActivityStoredFile", b =>
                {
                    b.Property<Guid>("CompletedActivityId")
                        .HasColumnType("uuid")
                        .HasColumnName("completed_activity_id");

                    b.Property<Guid>("StoredFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("stored_file_id");

                    b.HasKey("CompletedActivityId", "StoredFileId")
                        .HasName("pk_completed_activity_stored_files");

                    b.HasIndex("StoredFileId")
                        .HasDatabaseName("ix_completed_activity_stored_files_stored_file_id");

                    b.ToTable("completed_activity_stored_files", (string)null);
                });

            modelBuilder.Entity("EarlyLearner.Infrastructure.Persistence.Configurations.LearningContext.DailyLogConfig+DailyLogStoredFile", b =>
                {
                    b.Property<Guid>("DailyLogId")
                        .HasColumnType("uuid")
                        .HasColumnName("daily_log_id");

                    b.Property<Guid>("StoredFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("stored_file_id");

                    b.HasKey("DailyLogId", "StoredFileId")
                        .HasName("pk_daily_log_stored_files");

                    b.HasIndex("StoredFileId")
                        .HasDatabaseName("ix_daily_log_stored_files_stored_file_id");

                    b.ToTable("daily_log_stored_files", (string)null);
                });

            modelBuilder.Entity("EarlyLearner.Infrastructure.Persistence.Configurations.LearningContext.ObservationConfig+ObservationReadinessOutcome", b =>
                {
                    b.Property<Guid>("ObservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("observation_id");

                    b.Property<Guid>("ReadinessOutcomeId")
                        .HasColumnType("uuid")
                        .HasColumnName("readiness_outcome_id");

                    b.HasKey("ObservationId", "ReadinessOutcomeId")
                        .HasName("pk_observation_readiness_outcomes");

                    b.HasIndex("ReadinessOutcomeId")
                        .HasDatabaseName("ix_observation_readiness_outcomes_readiness_outcome_id");

                    b.ToTable("observation_readiness_outcomes", (string)null);
                });

            modelBuilder.Entity("EarlyLearner.Infrastructure.Persistence.Configurations.LearningContext.ObservationConfig+ObservationStoredFile", b =>
                {
                    b.Property<Guid>("ObservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("observation_id");

                    b.Property<Guid>("StoredFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("stored_file_id");

                    b.HasKey("ObservationId", "StoredFileId")
                        .HasName("pk_observation_stored_files");

                    b.HasIndex("StoredFileId")
                        .HasDatabaseName("ix_observation_stored_files_stored_file_id");

                    b.ToTable("observation_stored_files", (string)null);
                });

            modelBuilder.Entity("EarlyLearner.Infrastructure.Persistence.Configurations.LearningContext.ReadingEntryConfig+ReadingEntryStoredFile", b =>
                {
                    b.Property<Guid>("ReadingEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("reading_entry_id");

                    b.Property<Guid>("StoredFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("stored_file_id");

                    b.HasKey("ReadingEntryId", "StoredFileId")
                        .HasName("pk_reading_entry_stored_files");

                    b.HasIndex("StoredFileId")
                        .HasDatabaseName("ix_reading_entry_stored_files_stored_file_id");

                    b.ToTable("reading_entry_stored_files", (string)null);
                });

            modelBuilder.Entity("EarlyLearner.Infrastructure.Persistence.Configurations.LearningContext.RoutineEntryConfig+RoutineEntryStoredFile", b =>
                {
                    b.Property<Guid>("RoutineEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("routine_entry_id");

                    b.Property<Guid>("StoredFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("stored_file_id");

                    b.HasKey("RoutineEntryId", "StoredFileId")
                        .HasName("pk_routine_entry_stored_files");

                    b.HasIndex("StoredFileId")
                        .HasDatabaseName("ix_routine_entry_stored_files_stored_file_id");

                    b.ToTable("routine_entry_stored_files", (string)null);
                });

            modelBuilder.Entity("EarlyLearner.Infrastructure.Persistence.Configurations.PlanningContext.GoalConfig+GoalReadinessOutcome", b =>
                {
                    b.Property<Guid>("GoalId")
                        .HasColumnType("uuid")
                        .HasColumnName("goal_id");

                    b.Property<Guid>("ReadinessOutcomeId")
                        .HasColumnType("uuid")
                        .HasColumnName("readiness_outcome_id");

                    b.HasKey("GoalId", "ReadinessOutcomeId")
                        .HasName("pk_goal_readiness_outcomes");

                    b.HasIndex("ReadinessOutcomeId")
                        .HasDatabaseName("ix_goal_readiness_outcomes_readiness_outcome_id");

                    b.ToTable("goal_readiness_outcomes", (string)null);
                });

            modelBuilder.Entity("EarlyLearner.Infrastructure.Persistence.Configurations.PlanningContext.PlannedLearningSessionConfig+PlannedLearningSessionGoal", b =>
                {
                    b.Property<Guid>("PlannedLearningSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("planned_learning_session_id");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("uuid")
                        .HasColumnName("goal_id");

                    b.HasKey("PlannedLearningSessionId", "GoalId")
                        .HasName("pk_planned_learning_session_goals");

                    b.HasIndex("GoalId")
                        .HasDatabaseName("ix_planned_learning_session_goals_goal_id");

                    b.ToTable("planned_learning_session_goals", (string)null);
                });

            modelBuilder.Entity("EarlyLearner.Infrastructure.Persistence.Configurations.PlanningContext.PlannedLearningSessionConfig+PlannedLearningSessionReadinessOutcome", b =>
                {
                    b.Property<Guid>("PlannedLearningSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("planned_learning_session_id");

                    b.Property<Guid>("ReadinessOutcomeId")
                        .HasColumnType("uuid")
                        .HasColumnName("readiness_outcome_id");

                    b.HasKey("PlannedLearningSessionId", "ReadinessOutcomeId")
                        .HasName("pk_planned_learning_session_readiness_outcomes");

                    b.HasIndex("ReadinessOutcomeId")
                        .HasDatabaseName("ix_planned_learning_session_readiness_outcomes_readiness_outco");

                    b.ToTable("planned_learning_session_readiness_outcomes", (string)null);
                });

            modelBuilder.Entity("EarlyLearner.Infrastructure.Persistence.Configurations.ReadinessContext.PortfolioItemConfig+PortfolioItemReadinessOutcome", b =>
                {
                    b.Property<Guid>("PortfolioItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("portfolio_item_id");

                    b.Property<Guid>("ReadinessOutcomeId")
                        .HasColumnType("uuid")
                        .HasColumnName("readiness_outcome_id");

                    b.HasKey("PortfolioItemId", "ReadinessOutcomeId")
                        .HasName("pk_portfolio_item_readiness_outcomes");

                    b.HasIndex("ReadinessOutcomeId")
                        .HasDatabaseName("ix_portfolio_item_readiness_outcomes_readiness_outcome_id");

                    b.ToTable("portfolio_item_readiness_outcomes", (string)null);
                });

            modelBuilder.Entity("EarlyLearner.Infrastructure.Persistence.Configurations.ReadinessContext.PortfolioItemConfig+PortfolioItemStoredFile", b =>
                {
                    b.Property<Guid>("PortfolioItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("portfolio_item_id");

                    b.Property<Guid>("StoredFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("stored_file_id");

                    b.HasKey("PortfolioItemId", "StoredFileId")
                        .HasName("pk_portfolio_item_stored_files");

                    b.HasIndex("StoredFileId")
                        .HasDatabaseName("ix_portfolio_item_stored_files_stored_file_id");

                    b.ToTable("portfolio_item_stored_files", (string)null);
                });

            modelBuilder.Entity("EarlyLearner.Domain.CoreContext.Entities.StoredFile", b =>
                {
                    b.HasOne("EarlyLearner.Domain.IdentityContext.Entities.Household", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stored_files_households_household_id");

                    b.Navigation("Household");
                });

            modelBuilder.Entity("EarlyLearner.Domain.IdentityContext.Entities.Carer", b =>
                {
                    b.HasOne("EarlyLearner.Domain.IdentityContext.Entities.Household", "Household")
                        .WithMany("Carers")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_carers_households_household_id");

                    b.HasOne("EarlyLearner.Domain.IdentityContext.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_carers_users_user_id");

                    b.Navigation("Household");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EarlyLearner.Domain.IdentityContext.Entities.Child", b =>
                {
                    b.HasOne("EarlyLearner.Domain.IdentityContext.Entities.Household", "Household")
                        .WithMany("Children")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_children_households_household_id");

                    b.Navigation("Household");
                });

            modelBuilder.Entity("EarlyLearner.Domain.LearningContext.Entities.CompletedActivity", b =>
                {
                    b.HasOne("EarlyLearner.Domain.LearningContext.Entities.DailyLog", "DailyLog")
                        .WithMany("CompletedActivities")
                        .HasForeignKey("DailyLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_completed_activities_daily_logs_daily_log_id");

                    b.Navigation("DailyLog");
                });

            modelBuilder.Entity("EarlyLearner.Domain.LearningContext.Entities.DailyLog", b =>
                {
                    b.HasOne("EarlyLearner.Domain.IdentityContext.Entities.Child", "Child")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_daily_logs_children_child_id");

                    b.HasOne("EarlyLearner.Domain.IdentityContext.Entities.Household", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_daily_logs_households_household_id");

                    b.Navigation("Child");

                    b.Navigation("Household");
                });

            modelBuilder.Entity("EarlyLearner.Domain.LearningContext.Entities.Observation", b =>
                {
                    b.HasOne("EarlyLearner.Domain.IdentityContext.Entities.Child", "Child")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_observations_children_child_id");

                    b.HasOne("EarlyLearner.Domain.IdentityContext.Entities.Household", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_observations_households_household_id");

                    b.Navigation("Child");

                    b.Navigation("Household");
                });

            modelBuilder.Entity("EarlyLearner.Domain.LearningContext.Entities.ReadingEntry", b =>
                {
                    b.HasOne("EarlyLearner.Domain.LearningContext.Entities.DailyLog", "DailyLog")
                        .WithMany("ReadingEntries")
                        .HasForeignKey("DailyLogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reading_entries_daily_logs_daily_log_id");

                    b.Navigation("DailyLog");
                });

            modelBuilder.Entity("EarlyLearner.Domain.LearningContext.Entities.RoutineEntry", b =>
                {
                    b.HasOne("EarlyLearner.Domain.LearningContext.Entities.DailyLog", "DailyLog")
                        .WithMany("RoutineEntries")
                        .HasForeignKey("DailyLogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_routine_entries_daily_logs_daily_log_id");

                    b.Navigation("DailyLog");
                });

            modelBuilder.Entity("EarlyLearner.Domain.PlanningContext.Entities.Goal", b =>
                {
                    b.HasOne("EarlyLearner.Domain.IdentityContext.Entities.Child", "Child")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_goals_children_child_id");

                    b.HasOne("EarlyLearner.Domain.IdentityContext.Entities.Household", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_goals_households_household_id");

                    b.OwnsOne("EarlyLearner.Domain.CoreContext.DateRange", "Timeframe", b1 =>
                        {
                            b1.Property<Guid>("GoalId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateOnly>("EndDate")
                                .HasColumnType("date")
                                .HasColumnName("timeframe_end_date");

                            b1.Property<DateOnly>("StartDate")
                                .HasColumnType("date")
                                .HasColumnName("timeframe_start_date");

                            b1.HasKey("GoalId");

                            b1.ToTable("goals");

                            b1.WithOwner()
                                .HasForeignKey("GoalId")
                                .HasConstraintName("fk_goals_goals_id");
                        });

                    b.Navigation("Child");

                    b.Navigation("Household");

                    b.Navigation("Timeframe")
                        .IsRequired();
                });

            modelBuilder.Entity("EarlyLearner.Domain.PlanningContext.Entities.LearningPlan", b =>
                {
                    b.HasOne("EarlyLearner.Domain.IdentityContext.Entities.Child", "Child")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_learning_plans_children_child_id");

                    b.HasOne("EarlyLearner.Domain.IdentityContext.Entities.Household", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_learning_plans_households_household_id");

                    b.OwnsOne("EarlyLearner.Domain.CoreContext.DateRange", "Period", b1 =>
                        {
                            b1.Property<Guid>("LearningPlanId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateOnly>("EndDate")
                                .HasColumnType("date")
                                .HasColumnName("period_end_date");

                            b1.Property<DateOnly>("StartDate")
                                .HasColumnType("date")
                                .HasColumnName("period_start_date");

                            b1.HasKey("LearningPlanId");

                            b1.ToTable("learning_plans");

                            b1.WithOwner()
                                .HasForeignKey("LearningPlanId")
                                .HasConstraintName("fk_learning_plans_learning_plans_id");
                        });

                    b.Navigation("Child");

                    b.Navigation("Household");

                    b.Navigation("Period")
                        .IsRequired();
                });

            modelBuilder.Entity("EarlyLearner.Domain.PlanningContext.Entities.PlannedLearningSession", b =>
                {
                    b.HasOne("EarlyLearner.Domain.PlanningContext.Entities.LearningPlan", "LearningPlan")
                        .WithMany("Sessions")
                        .HasForeignKey("LearningPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_planned_learning_sessions_learning_plans_learning_plan_id");

                    b.Navigation("LearningPlan");
                });

            modelBuilder.Entity("EarlyLearner.Domain.ReadinessContext.Entities.EvidenceReference", b =>
                {
                    b.HasOne("EarlyLearner.Domain.ReadinessContext.Entities.ReadinessOutcome", "ReadinessOutcome")
                        .WithMany()
                        .HasForeignKey("ReadinessOutcomeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_evidence_references_readiness_outcomes_readiness_outcome_id");

                    b.HasOne("EarlyLearner.Domain.ReadinessContext.Entities.ReadinessOutcomeProgress", "ReadinessOutcomeProgress")
                        .WithMany("Evidence")
                        .HasForeignKey("ReadinessOutcomeProgressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_evidence_references_readiness_outcome_progress_readiness_ou");

                    b.Navigation("ReadinessOutcome");

                    b.Navigation("ReadinessOutcomeProgress");
                });

            modelBuilder.Entity("EarlyLearner.Domain.ReadinessContext.Entities.PortfolioItem", b =>
                {
                    b.HasOne("EarlyLearner.Domain.IdentityContext.Entities.Child", "Child")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_portfolio_items_children_child_id");

                    b.HasOne("EarlyLearner.Domain.IdentityContext.Entities.Household", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_portfolio_items_households_household_id");

                    b.OwnsOne("EarlyLearner.Domain.ReadinessContext.ValueObjects.PortfolioEvidenceSource", "Source", b1 =>
                        {
                            b1.Property<Guid>("PortfolioItemId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("EvidenceRecordId")
                                .HasColumnType("uuid")
                                .HasColumnName("source_evidence_record_id");

                            b1.Property<DateOnly>("SourceDate")
                                .HasColumnType("date")
                                .HasColumnName("source_source_date");

                            b1.Property<string>("SourceType")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("source_source_type");

                            b1.HasKey("PortfolioItemId");

                            b1.ToTable("portfolio_items");

                            b1.WithOwner()
                                .HasForeignKey("PortfolioItemId")
                                .HasConstraintName("fk_portfolio_items_portfolio_items_id");
                        });

                    b.Navigation("Child");

                    b.Navigation("Household");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("EarlyLearner.Domain.ReadinessContext.Entities.ReadinessOutcomeProgress", b =>
                {
                    b.HasOne("EarlyLearner.Domain.ReadinessContext.Entities.ReadinessOutcome", "ReadinessOutcome")
                        .WithMany()
                        .HasForeignKey("ReadinessOutcomeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_readiness_outcome_progresses_readiness_outcomes_readiness_o");

                    b.HasOne("EarlyLearner.Domain.ReadinessContext.Entities.ReadinessProfile", "ReadinessProfile")
                        .WithMany("OutcomeProgress")
                        .HasForeignKey("ReadinessProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_readiness_outcome_progresses_readiness_profiles_readiness_p");

                    b.Navigation("ReadinessOutcome");

                    b.Navigation("ReadinessProfile");
                });

            modelBuilder.Entity("EarlyLearner.Domain.ReadinessContext.Entities.ReadinessProfile", b =>
                {
                    b.HasOne("EarlyLearner.Domain.IdentityContext.Entities.Child", "Child")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_readiness_profiles_children_child_id");

                    b.HasOne("EarlyLearner.Domain.IdentityContext.Entities.Household", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_readiness_profiles_households_household_id");

                    b.Navigation("Child");

                    b.Navigation("Household");
                });

            modelBuilder.Entity("EarlyLearner.Domain.ReadinessContext.Entities.SuggestedNextStep", b =>
                {
                    b.HasOne("EarlyLearner.Domain.ReadinessContext.Entities.ReadinessOutcome", "ReadinessOutcome")
                        .WithMany()
                        .HasForeignKey("ReadinessOutcomeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_suggested_next_steps_readiness_outcomes_readiness_outcome_id");

                    b.HasOne("EarlyLearner.Domain.ReadinessContext.Entities.ReadinessProfile", "ReadinessProfile")
                        .WithMany("SuggestedNextSteps")
                        .HasForeignKey("ReadinessProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_suggested_next_steps_readiness_profiles_readiness_profile_id");

                    b.Navigation("ReadinessOutcome");

                    b.Navigation("ReadinessProfile");
                });

            modelBuilder.Entity("EarlyLearner.Infrastructure.Persistence.Configurations.LearningContext.CompletedActivityConfig+CompletedActivityReadinessOutcome", b =>
                {
                    b.HasOne("EarlyLearner.Domain.LearningContext.Entities.CompletedActivity", "CompletedActivity")
                        .WithMany()
                        .HasForeignKey("CompletedActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_completed_activity_readiness_outcomes_completed_activities_");

                    b.HasOne("EarlyLearner.Domain.ReadinessContext.Entities.ReadinessOutcome", "ReadinessOutcome")
                        .WithMany()
                        .HasForeignKey("ReadinessOutcomeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_completed_activity_readiness_outcomes_readiness_outcomes_re");

                    b.Navigation("CompletedActivity");

                    b.Navigation("ReadinessOutcome");
                });

            modelBuilder.Entity("EarlyLearner.Infrastructure.Persistence.Configurations.LearningContext.CompletedActivityConfig+CompletedActivityStoredFile", b =>
                {
                    b.HasOne("EarlyLearner.Domain.LearningContext.Entities.CompletedActivity", "CompletedActivity")
                        .WithMany()
                        .HasForeignKey("CompletedActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_completed_activity_stored_files_completed_activities_comple");

                    b.HasOne("EarlyLearner.Domain.CoreContext.Entities.StoredFile", "StoredFile")
                        .WithMany()
                        .HasForeignKey("StoredFileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_completed_activity_stored_files_stored_files_stored_file_id");

                    b.Navigation("CompletedActivity");

                    b.Navigation("StoredFile");
                });

            modelBuilder.Entity("EarlyLearner.Infrastructure.Persistence.Configurations.LearningContext.DailyLogConfig+DailyLogStoredFile", b =>
                {
                    b.HasOne("EarlyLearner.Domain.LearningContext.Entities.DailyLog", "DailyLog")
                        .WithMany()
                        .HasForeignKey("DailyLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_daily_log_stored_files_daily_logs_daily_log_id");

                    b.HasOne("EarlyLearner.Domain.CoreContext.Entities.StoredFile", "StoredFile")
                        .WithMany()
                        .HasForeignKey("StoredFileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_daily_log_stored_files_stored_files_stored_file_id");

                    b.Navigation("DailyLog");

                    b.Navigation("StoredFile");
                });

            modelBuilder.Entity("EarlyLearner.Infrastructure.Persistence.Configurations.LearningContext.ObservationConfig+ObservationReadinessOutcome", b =>
                {
                    b.HasOne("EarlyLearner.Domain.LearningContext.Entities.Observation", "Observation")
                        .WithMany()
                        .HasForeignKey("ObservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_observation_readiness_outcomes_observations_observation_id");

                    b.HasOne("EarlyLearner.Domain.ReadinessContext.Entities.ReadinessOutcome", "ReadinessOutcome")
                        .WithMany()
                        .HasForeignKey("ReadinessOutcomeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_observation_readiness_outcomes_readiness_outcomes_readiness");

                    b.Navigation("Observation");

                    b.Navigation("ReadinessOutcome");
                });

            modelBuilder.Entity("EarlyLearner.Infrastructure.Persistence.Configurations.LearningContext.ObservationConfig+ObservationStoredFile", b =>
                {
                    b.HasOne("EarlyLearner.Domain.LearningContext.Entities.Observation", "Observation")
                        .WithMany()
                        .HasForeignKey("ObservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_observation_stored_files_observations_observation_id");

                    b.HasOne("EarlyLearner.Domain.CoreContext.Entities.StoredFile", "StoredFile")
                        .WithMany()
                        .HasForeignKey("StoredFileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_observation_stored_files_stored_files_stored_file_id");

                    b.Navigation("Observation");

                    b.Navigation("StoredFile");
                });

            modelBuilder.Entity("EarlyLearner.Infrastructure.Persistence.Configurations.LearningContext.ReadingEntryConfig+ReadingEntryStoredFile", b =>
                {
                    b.HasOne("EarlyLearner.Domain.LearningContext.Entities.ReadingEntry", "ReadingEntry")
                        .WithMany()
                        .HasForeignKey("ReadingEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reading_entry_stored_files_reading_entries_reading_entry_id");

                    b.HasOne("EarlyLearner.Domain.CoreContext.Entities.StoredFile", "StoredFile")
                        .WithMany()
                        .HasForeignKey("StoredFileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reading_entry_stored_files_stored_files_stored_file_id");

                    b.Navigation("ReadingEntry");

                    b.Navigation("StoredFile");
                });

            modelBuilder.Entity("EarlyLearner.Infrastructure.Persistence.Configurations.LearningContext.RoutineEntryConfig+RoutineEntryStoredFile", b =>
                {
                    b.HasOne("EarlyLearner.Domain.LearningContext.Entities.RoutineEntry", "RoutineEntry")
                        .WithMany()
                        .HasForeignKey("RoutineEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_routine_entry_stored_files_routine_entries_routine_entry_id");

                    b.HasOne("EarlyLearner.Domain.CoreContext.Entities.StoredFile", "StoredFile")
                        .WithMany()
                        .HasForeignKey("StoredFileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_routine_entry_stored_files_stored_files_stored_file_id");

                    b.Navigation("RoutineEntry");

                    b.Navigation("StoredFile");
                });

            modelBuilder.Entity("EarlyLearner.Infrastructure.Persistence.Configurations.PlanningContext.GoalConfig+GoalReadinessOutcome", b =>
                {
                    b.HasOne("EarlyLearner.Domain.PlanningContext.Entities.Goal", "Goal")
                        .WithMany()
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_goal_readiness_outcomes_goals_goal_id");

                    b.HasOne("EarlyLearner.Domain.ReadinessContext.Entities.ReadinessOutcome", "ReadinessOutcome")
                        .WithMany()
                        .HasForeignKey("ReadinessOutcomeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_goal_readiness_outcomes_readiness_outcomes_readiness_outcom");

                    b.Navigation("Goal");

                    b.Navigation("ReadinessOutcome");
                });

            modelBuilder.Entity("EarlyLearner.Infrastructure.Persistence.Configurations.PlanningContext.PlannedLearningSessionConfig+PlannedLearningSessionGoal", b =>
                {
                    b.HasOne("EarlyLearner.Domain.PlanningContext.Entities.Goal", "Goal")
                        .WithMany()
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_planned_learning_session_goals_goals_goal_id");

                    b.HasOne("EarlyLearner.Domain.PlanningContext.Entities.PlannedLearningSession", "PlannedLearningSession")
                        .WithMany()
                        .HasForeignKey("PlannedLearningSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_planned_learning_session_goals_planned_learning_sessions_pl");

                    b.Navigation("Goal");

                    b.Navigation("PlannedLearningSession");
                });

            modelBuilder.Entity("EarlyLearner.Infrastructure.Persistence.Configurations.PlanningContext.PlannedLearningSessionConfig+PlannedLearningSessionReadinessOutcome", b =>
                {
                    b.HasOne("EarlyLearner.Domain.PlanningContext.Entities.PlannedLearningSession", "PlannedLearningSession")
                        .WithMany()
                        .HasForeignKey("PlannedLearningSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_planned_learning_session_readiness_outcomes_planned_learnin");

                    b.HasOne("EarlyLearner.Domain.ReadinessContext.Entities.ReadinessOutcome", "ReadinessOutcome")
                        .WithMany()
                        .HasForeignKey("ReadinessOutcomeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_planned_learning_session_readiness_outcomes_readiness_outco");

                    b.Navigation("PlannedLearningSession");

                    b.Navigation("ReadinessOutcome");
                });

            modelBuilder.Entity("EarlyLearner.Infrastructure.Persistence.Configurations.ReadinessContext.PortfolioItemConfig+PortfolioItemReadinessOutcome", b =>
                {
                    b.HasOne("EarlyLearner.Domain.ReadinessContext.Entities.PortfolioItem", "PortfolioItem")
                        .WithMany()
                        .HasForeignKey("PortfolioItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_portfolio_item_readiness_outcomes_portfolio_items_portfolio");

                    b.HasOne("EarlyLearner.Domain.ReadinessContext.Entities.ReadinessOutcome", "ReadinessOutcome")
                        .WithMany()
                        .HasForeignKey("ReadinessOutcomeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_portfolio_item_readiness_outcomes_readiness_outcomes_readin");

                    b.Navigation("PortfolioItem");

                    b.Navigation("ReadinessOutcome");
                });

            modelBuilder.Entity("EarlyLearner.Infrastructure.Persistence.Configurations.ReadinessContext.PortfolioItemConfig+PortfolioItemStoredFile", b =>
                {
                    b.HasOne("EarlyLearner.Domain.ReadinessContext.Entities.PortfolioItem", "PortfolioItem")
                        .WithMany()
                        .HasForeignKey("PortfolioItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_portfolio_item_stored_files_portfolio_items_portfolio_item_");

                    b.HasOne("EarlyLearner.Domain.CoreContext.Entities.StoredFile", "StoredFile")
                        .WithMany()
                        .HasForeignKey("StoredFileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_portfolio_item_stored_files_stored_files_stored_file_id");

                    b.Navigation("PortfolioItem");

                    b.Navigation("StoredFile");
                });

            modelBuilder.Entity("EarlyLearner.Domain.IdentityContext.Entities.Household", b =>
                {
                    b.Navigation("Carers");

                    b.Navigation("Children");
                });

            modelBuilder.Entity("EarlyLearner.Domain.LearningContext.Entities.DailyLog", b =>
                {
                    b.Navigation("CompletedActivities");

                    b.Navigation("ReadingEntries");

                    b.Navigation("RoutineEntries");
                });

            modelBuilder.Entity("EarlyLearner.Domain.PlanningContext.Entities.LearningPlan", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("EarlyLearner.Domain.ReadinessContext.Entities.ReadinessOutcomeProgress", b =>
                {
                    b.Navigation("Evidence");
                });

            modelBuilder.Entity("EarlyLearner.Domain.ReadinessContext.Entities.ReadinessProfile", b =>
                {
                    b.Navigation("OutcomeProgress");

                    b.Navigation("SuggestedNextSteps");
                });
#pragma warning restore 612, 618
        }
    }
}
