// <auto-generated />
using System;
using EarlyLearner.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EarlyLearner.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EarlyLearner.Domain.CoreContext.Entities.StoredFile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("file_name");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("media_type");

                    b.Property<long>("SizeInBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_in_bytes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_key");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id")
                        .HasName("pk_stored_files");

                    b.HasIndex("HouseholdId", "StorageKey")
                        .IsUnique()
                        .HasDatabaseName("ix_stored_files_household_id_storage_key");

                    b.ToTable("stored_files", (string)null);
                });

            modelBuilder.Entity("EarlyLearner.Domain.IdentityContext.Entities.Carer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_carers");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_carers_user_id");

                    b.HasIndex("HouseholdId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_carers_household_id_user_id");

                    b.ToTable("carers", (string)null);
                });

            modelBuilder.Entity("EarlyLearner.Domain.IdentityContext.Entities.Child", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AvatarStoredFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("avatar_stored_file_id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("first_name");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("last_name");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id")
                        .HasName("pk_children");

                    b.HasIndex("HouseholdId", "FirstName")
                        .HasDatabaseName("ix_children_household_id_first_name");

                    b.ToTable("children", (string)null);
                });

            modelBuilder.Entity("EarlyLearner.Domain.IdentityContext.Entities.Household", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id")
                        .HasName("pk_households");

                    b.ToTable("households", (string)null);
                });

            modelBuilder.Entity("EarlyLearner.Domain.IdentityContext.Entities.HouseholdInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<Guid?>("AcceptedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("accepted_by_user_id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<DateTimeOffset>("InvitedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invited_at");

                    b.Property<Guid>("InvitedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_by_user_id");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id")
                        .HasName("pk_household_invitations");

                    b.HasIndex("InvitedByUserId")
                        .HasDatabaseName("ix_household_invitations_invited_by_user_id");

                    b.HasIndex("HouseholdId", "Email", "Status")
                        .HasDatabaseName("ix_household_invitations_household_id_email_status");

                    b.ToTable("household_invitations", (string)null);
                });

            modelBuilder.Entity("EarlyLearner.Domain.IdentityContext.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("ExternalObjectId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_object_id");

                    b.Property<string>("ExternalTenantId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_tenant_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("ExternalObjectId", "ExternalTenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_external_object_id_external_tenant_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("EarlyLearner.Domain.LearningContext.Entities.DailyLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<DateOnly>("LogDate")
                        .HasColumnType("date")
                        .HasColumnName("log_date");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id")
                        .HasName("pk_daily_logs");

                    b.HasIndex("ChildId")
                        .HasDatabaseName("ix_daily_logs_child_id");

                    b.HasIndex("HouseholdId", "ChildId", "LogDate")
                        .IsUnique()
                        .HasDatabaseName("ix_daily_logs_household_id_child_id_log_date");

                    b.ToTable("daily_logs", (string)null);
                });

            modelBuilder.Entity("EarlyLearner.Domain.LearningContext.Entities.LearningMoment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<Guid>("DailyLogId")
                        .HasColumnType("uuid")
                        .HasColumnName("daily_log_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("kind");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id")
                        .HasName("pk_learning_moments");

                    b.HasIndex("DailyLogId")
                        .HasDatabaseName("ix_learning_moments_daily_log_id");

                    b.ToTable("learning_moments", (string)null);
                });

            modelBuilder.Entity("EarlyLearner.Domain.ReadinessContext.Entities.ReadinessEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<Guid>("EvidenceRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("evidence_record_id");

                    b.Property<DateOnly>("ObservedOn")
                        .HasColumnType("date")
                        .HasColumnName("observed_on");

                    b.Property<Guid>("ReadinessOutcomeId")
                        .HasColumnType("uuid")
                        .HasColumnName("readiness_outcome_id");

                    b.Property<Guid>("ReadinessProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("readiness_profile_id");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("source_type");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)")
                        .HasColumnName("summary");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id")
                        .HasName("pk_readiness_evidences");

                    b.HasIndex("ReadinessOutcomeId")
                        .HasDatabaseName("ix_readiness_evidences_readiness_outcome_id");

                    b.HasIndex("ReadinessProfileId")
                        .HasDatabaseName("ix_readiness_evidences_readiness_profile_id");

                    b.ToTable("readiness_evidences", (string)null);
                });

            modelBuilder.Entity("EarlyLearner.Domain.ReadinessContext.Entities.ReadinessOutcome", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("character varying(1200)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id")
                        .HasName("pk_readiness_outcomes");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_readiness_outcomes_code");

                    b.HasIndex("Category", "SortOrder")
                        .HasDatabaseName("ix_readiness_outcomes_category_sort_order");

                    b.ToTable("readiness_outcomes", (string)null);
                });

            modelBuilder.Entity("EarlyLearner.Domain.ReadinessContext.Entities.ReadinessProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id")
                        .HasName("pk_readiness_profiles");

                    b.HasIndex("ChildId")
                        .HasDatabaseName("ix_readiness_profiles_child_id");

                    b.HasIndex("HouseholdId", "ChildId")
                        .IsUnique()
                        .HasDatabaseName("ix_readiness_profiles_household_id_child_id");

                    b.ToTable("readiness_profiles", (string)null);
                });

            modelBuilder.Entity("EarlyLearner.Domain.ReadinessContext.Entities.TrackedReadinessOutcome", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ReadinessOutcomeId")
                        .HasColumnType("uuid")
                        .HasColumnName("readiness_outcome_id");

                    b.Property<Guid>("ReadinessProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("readiness_profile_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_tracked_readiness_outcomes");

                    b.HasIndex("ReadinessOutcomeId")
                        .HasDatabaseName("ix_tracked_readiness_outcomes_readiness_outcome_id");

                    b.HasIndex("ReadinessProfileId", "ReadinessOutcomeId")
                        .IsUnique()
                        .HasDatabaseName("ix_tracked_readiness_outcomes_readiness_profile_id_readiness_o");

                    b.ToTable("tracked_readiness_outcomes", (string)null);
                });

            modelBuilder.Entity("EarlyLearner.Infrastructure.Persistence.Configurations.LearningContext.LearningMomentConfig+LearningMomentReadinessOutcome", b =>
                {
                    b.Property<Guid>("LearningMomentId")
                        .HasColumnType("uuid")
                        .HasColumnName("learning_moment_id");

                    b.Property<Guid>("ReadinessOutcomeId")
                        .HasColumnType("uuid")
                        .HasColumnName("readiness_outcome_id");

                    b.HasKey("LearningMomentId", "ReadinessOutcomeId")
                        .HasName("pk_learning_moment_readiness_outcomes");

                    b.HasIndex("ReadinessOutcomeId")
                        .HasDatabaseName("ix_learning_moment_readiness_outcomes_readiness_outcome_id");

                    b.ToTable("learning_moment_readiness_outcomes", (string)null);
                });

            modelBuilder.Entity("EarlyLearner.Infrastructure.Persistence.Configurations.LearningContext.LearningMomentConfig+LearningMomentStoredFile", b =>
                {
                    b.Property<Guid>("LearningMomentId")
                        .HasColumnType("uuid")
                        .HasColumnName("learning_moment_id");

                    b.Property<Guid>("StoredFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("stored_file_id");

                    b.HasKey("LearningMomentId", "StoredFileId")
                        .HasName("pk_learning_moment_stored_files");

                    b.HasIndex("StoredFileId")
                        .HasDatabaseName("ix_learning_moment_stored_files_stored_file_id");

                    b.ToTable("learning_moment_stored_files", (string)null);
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.InboxState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Consumed")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid")
                        .HasColumnName("consumer_id");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration_time");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("last_sequence_number");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid")
                        .HasColumnName("lock_id");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<int>("ReceiveCount")
                        .HasColumnType("integer")
                        .HasColumnName("receive_count");

                    b.Property<DateTime>("Received")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.HasKey("Id")
                        .HasName("pk_inbox_state");

                    b.HasAlternateKey("MessageId", "ConsumerId")
                        .HasName("ak_inbox_state_message_id_consumer_id");

                    b.HasIndex("Delivered")
                        .HasDatabaseName("ix_inbox_state_delivered");

                    b.ToTable("inbox_state", (string)null);
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sequence_number");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("content_type");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("destination_address");

                    b.Property<DateTime?>("EnqueueTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enqueue_time");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration_time");

                    b.Property<string>("FaultAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("fault_address");

                    b.Property<string>("Headers")
                        .HasColumnType("text")
                        .HasColumnName("headers");

                    b.Property<Guid?>("InboxConsumerId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbox_consumer_id");

                    b.Property<Guid?>("InboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbox_message_id");

                    b.Property<Guid?>("InitiatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("initiator_id");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_type");

                    b.Property<Guid?>("OutboxId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_id");

                    b.Property<string>("Properties")
                        .HasColumnType("text")
                        .HasColumnName("properties");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<string>("ResponseAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("response_address");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_time");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source_address");

                    b.HasKey("SequenceNumber")
                        .HasName("pk_outbox_message");

                    b.HasIndex("EnqueueTime")
                        .HasDatabaseName("ix_outbox_message_enqueue_time");

                    b.HasIndex("ExpirationTime")
                        .HasDatabaseName("ix_outbox_message_expiration_time");

                    b.HasIndex("OutboxId", "SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_outbox_message_outbox_id_sequence_number");

                    b.HasIndex("InboxMessageId", "InboxConsumerId", "SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_outbox_message_inbox_message_id_inbox_consumer_id_sequence_");

                    b.ToTable("outbox_message", (string)null);
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxState", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("last_sequence_number");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid")
                        .HasColumnName("lock_id");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.HasKey("OutboxId")
                        .HasName("pk_outbox_state");

                    b.HasIndex("Created")
                        .HasDatabaseName("ix_outbox_state_created");

                    b.ToTable("outbox_state", (string)null);
                });

            modelBuilder.Entity("EarlyLearner.Domain.CoreContext.Entities.StoredFile", b =>
                {
                    b.HasOne("EarlyLearner.Domain.IdentityContext.Entities.Household", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stored_files_households_household_id");

                    b.Navigation("Household");
                });

            modelBuilder.Entity("EarlyLearner.Domain.IdentityContext.Entities.Carer", b =>
                {
                    b.HasOne("EarlyLearner.Domain.IdentityContext.Entities.Household", "Household")
                        .WithMany("Carers")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_carers_households_household_id");

                    b.HasOne("EarlyLearner.Domain.IdentityContext.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_carers_users_user_id");

                    b.Navigation("Household");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EarlyLearner.Domain.IdentityContext.Entities.Child", b =>
                {
                    b.HasOne("EarlyLearner.Domain.IdentityContext.Entities.Household", "Household")
                        .WithMany("Children")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_children_households_household_id");

                    b.Navigation("Household");
                });

            modelBuilder.Entity("EarlyLearner.Domain.IdentityContext.Entities.HouseholdInvitation", b =>
                {
                    b.HasOne("EarlyLearner.Domain.IdentityContext.Entities.Household", "Household")
                        .WithMany("Invitations")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_household_invitations_households_household_id");

                    b.HasOne("EarlyLearner.Domain.IdentityContext.Entities.User", "InvitedByUser")
                        .WithMany()
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_household_invitations_users_invited_by_user_id");

                    b.Navigation("Household");

                    b.Navigation("InvitedByUser");
                });

            modelBuilder.Entity("EarlyLearner.Domain.LearningContext.Entities.DailyLog", b =>
                {
                    b.HasOne("EarlyLearner.Domain.IdentityContext.Entities.Child", "Child")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_daily_logs_children_child_id");

                    b.HasOne("EarlyLearner.Domain.IdentityContext.Entities.Household", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_daily_logs_households_household_id");

                    b.Navigation("Child");

                    b.Navigation("Household");
                });

            modelBuilder.Entity("EarlyLearner.Domain.LearningContext.Entities.LearningMoment", b =>
                {
                    b.HasOne("EarlyLearner.Domain.LearningContext.Entities.DailyLog", "DailyLog")
                        .WithMany("LearningMoments")
                        .HasForeignKey("DailyLogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_learning_moments_daily_logs_daily_log_id");

                    b.Navigation("DailyLog");
                });

            modelBuilder.Entity("EarlyLearner.Domain.ReadinessContext.Entities.ReadinessEvidence", b =>
                {
                    b.HasOne("EarlyLearner.Domain.ReadinessContext.Entities.ReadinessOutcome", "ReadinessOutcome")
                        .WithMany()
                        .HasForeignKey("ReadinessOutcomeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_readiness_evidences_readiness_outcomes_readiness_outcome_id");

                    b.HasOne("EarlyLearner.Domain.ReadinessContext.Entities.ReadinessProfile", "ReadinessProfile")
                        .WithMany("Evidence")
                        .HasForeignKey("ReadinessProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_readiness_evidences_readiness_profiles_readiness_profile_id");

                    b.Navigation("ReadinessOutcome");

                    b.Navigation("ReadinessProfile");
                });

            modelBuilder.Entity("EarlyLearner.Domain.ReadinessContext.Entities.ReadinessProfile", b =>
                {
                    b.HasOne("EarlyLearner.Domain.IdentityContext.Entities.Child", "Child")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_readiness_profiles_children_child_id");

                    b.HasOne("EarlyLearner.Domain.IdentityContext.Entities.Household", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_readiness_profiles_households_household_id");

                    b.Navigation("Child");

                    b.Navigation("Household");
                });

            modelBuilder.Entity("EarlyLearner.Domain.ReadinessContext.Entities.TrackedReadinessOutcome", b =>
                {
                    b.HasOne("EarlyLearner.Domain.ReadinessContext.Entities.ReadinessOutcome", "ReadinessOutcome")
                        .WithMany()
                        .HasForeignKey("ReadinessOutcomeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tracked_readiness_outcomes_readiness_outcomes_readiness_out");

                    b.HasOne("EarlyLearner.Domain.ReadinessContext.Entities.ReadinessProfile", "ReadinessProfile")
                        .WithMany("TrackedOutcomes")
                        .HasForeignKey("ReadinessProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tracked_readiness_outcomes_readiness_profiles_readiness_pro");

                    b.Navigation("ReadinessOutcome");

                    b.Navigation("ReadinessProfile");
                });

            modelBuilder.Entity("EarlyLearner.Infrastructure.Persistence.Configurations.LearningContext.LearningMomentConfig+LearningMomentReadinessOutcome", b =>
                {
                    b.HasOne("EarlyLearner.Domain.LearningContext.Entities.LearningMoment", "LearningMoment")
                        .WithMany()
                        .HasForeignKey("LearningMomentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_learning_moment_readiness_outcomes_learning_moments_learnin");

                    b.HasOne("EarlyLearner.Domain.ReadinessContext.Entities.ReadinessOutcome", "ReadinessOutcome")
                        .WithMany()
                        .HasForeignKey("ReadinessOutcomeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_learning_moment_readiness_outcomes_readiness_outcomes_readi");

                    b.Navigation("LearningMoment");

                    b.Navigation("ReadinessOutcome");
                });

            modelBuilder.Entity("EarlyLearner.Infrastructure.Persistence.Configurations.LearningContext.LearningMomentConfig+LearningMomentStoredFile", b =>
                {
                    b.HasOne("EarlyLearner.Domain.LearningContext.Entities.LearningMoment", "LearningMoment")
                        .WithMany()
                        .HasForeignKey("LearningMomentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_learning_moment_stored_files_learning_moments_learning_mome");

                    b.HasOne("EarlyLearner.Domain.CoreContext.Entities.StoredFile", "StoredFile")
                        .WithMany()
                        .HasForeignKey("StoredFileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_learning_moment_stored_files_stored_files_stored_file_id");

                    b.Navigation("LearningMoment");

                    b.Navigation("StoredFile");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.OutboxState", null)
                        .WithMany()
                        .HasForeignKey("OutboxId")
                        .HasConstraintName("fk_outbox_message_outbox_state_outbox_id");

                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.InboxState", null)
                        .WithMany()
                        .HasForeignKey("InboxMessageId", "InboxConsumerId")
                        .HasPrincipalKey("MessageId", "ConsumerId")
                        .HasConstraintName("fk_outbox_message_inbox_state_inbox_message_id_inbox_consumer_");
                });

            modelBuilder.Entity("EarlyLearner.Domain.IdentityContext.Entities.Household", b =>
                {
                    b.Navigation("Carers");

                    b.Navigation("Children");

                    b.Navigation("Invitations");
                });

            modelBuilder.Entity("EarlyLearner.Domain.LearningContext.Entities.DailyLog", b =>
                {
                    b.Navigation("LearningMoments");
                });

            modelBuilder.Entity("EarlyLearner.Domain.ReadinessContext.Entities.ReadinessProfile", b =>
                {
                    b.Navigation("Evidence");

                    b.Navigation("TrackedOutcomes");
                });
#pragma warning restore 612, 618
        }
    }
}
